### ISSUE TITLE
Bind JWT tokens in Scorer UI (and for the partner API) to the client IP

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#1064]
### User Story:
As a end user who is logged int o the scorer UI
I want that my session is only valid for the IP address from which I am currently connected

### Acceptance Criteria

GIVEN that I have SIWE and am logged into the scorer UI
WHEN I change my IP address
THEN the session tokens are no longer valid for that particular IP address
AND I am redirected to the landing page and I need to SIWE again

#### Product & Design Links:
<links>

**Comment by lucianHymer** [comment]
Tim and I talked about this and decided it'd be better to do the original request and add an IP address to the JWT we're creating.

- Storing data in a cookie lets us avoid XSS vulnerabilities, but we don't display user-generated content or anything like that so we probably aren't vulnerable to this kind of attack
- In the Linus example, the key was stole using spyware that directly accessed browser data, and localstorage and cookies seem like they'd be equally susceptible to this kind of attack
- Native apps don't support cookies, if we ever decide to go that direction

However, this does mean that users will need to log in again if their IP changes, such as switching from wifi to data on your phone, or going to a coffee shop and connecting to the wifi there, or sometimes just moving to a different cell tower. This is probably worth the trade-off, since the alternative is short cookie life-span which would be a worse user experience.

**Comment by nutrina** [comment]
Some information I have found regarding this topic:
- https://medium.com/@adarsh.pradyut/ip-bound-jwt-6e2669d15391
-
