### ISSUE TITLE
Understanding the Scope of StakeDashboard.jsx Component in GTC Staking App

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1220]
**Objective:**
The objective of this SPIKE is to investigate the functionality of the StakeDashboard.jsx component in the GTC staking app and determine whether it shows data just for the current round, or if it also pulls in data from old rounds and contracts.

**Scope:**

- Examine the StakeDashboard.jsx component code in the GTC staking app repository: https://github.com/gitcoinco/id-staking/blob/3233747ee4b00057550f9a2268decb95b0eb5dc2/packages/react-app/src/views/StakeDashboard.jsx
- Identify how the component fetches and displays staking data.
- Determine if the component shows data for only the current round or also includes data from previous rounds and contracts.

**Deliverables:**

- A detailed explanation of the functionality of the StakeDashboard.jsx component in the GTC staking app.
- A conclusion on whether the component displays data for just the current round, or also includes data from old rounds and contracts.

**Comment by michaelgreen06** [comment]
**DETAILED `Stakedashboard` explanation:**
When the `roundId` is changed via the `roundSelector` component at the bottom of the `stakedashboard` component it sets the `roundInView` value using the `setRoundInView` function which updates the `roundInView` value in the web3context helper function. The `stakedashboard` consumes the new `roundInView` value from web3context which then triggers two  `useEffect` hooks to run.

The first hook fetches the round data (start, duration, meta) directly from the smart contract using the contract’s `fetchroundmeta` function with the new `roundInView` value. This fetches the round data used to update the Grants round name and the start & end times of the round in the header of the dashboard. These new values are all state variables of `stakedashboard` and since they are changing, they cause it to re-render.

The second hook fetches the user’s stake data for the new `roundInView` value by using the `getData()` function which queries the Graph to get the data. This new data is displayed when the stake dashboard re-renders.

**Conclusion**
The `stakeDashboard` component currently displays data for the Beta round by default but can also display data for the Alpha round. To enable the component to show data from all other rounds would be slightly complex since they used different smart contract/s.
