### ISSUE TITLE
Integrate Phi stamp in Passport

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1233]
### User Story:
As a user and member of Phi https://quest.philand.xyz/
I want to verify my quest activity within Philand
So that I can prove I am a unique human and earn more stamps

### Acceptance Criteria
GIVEN I have a Phi account AND
GIVEN I have quest activity that exceeds the credential details
WHEN I verify my stamp
THEN I should earn the credential(s) of Phi

Verifications / credentials should include:
- Achieve Active Rank Silver I (Earn 65,000 EXP on Active Score)
- Achieve Active Rank Gold I (Earn 150,000 EXP on Active Score)

Each should be an independent VC (e.g. separate toggle/checkbox on sidebar)
This should be featured flagged OFF for Production (We'll want to wait until Alex can review and score before turning it on for users)

#### Product & Design Links:
<links>

#### Tech Details:
- Verify the identity record they're using to produce the credential hash and see whether it's deterministic and unique per record
- Phi team have created a PR -> https://github.com/gitcoinco/passport/pull/1232

#### Notes/Assumptions:
- This depends on #1124

**Comment by nutrina** [comment]
# PHIActivitySilver

- [ ] Verification payload
    ```json
    valid: true / false,
    record: {
       ... // Unique payload identifying user
    }
    ```
- [ ] the attribute `valid` must always be false if the stamp verification fails
- [ ] record must contain the following attributes:
    - 1 or more attributes uniquely identifying the user:
        - an ETH address - it should always be lower case (not checksummed)
        - an email (in case of Google for example)
        - the users unique ID (like for Facebook, Twitter, Github)        
- [ ] never should the payload contain a field named `pii`
    - this field is reserved for internal use
- [ ] the provider name must be globally unique (and should not have been used). This is because the provider name will be included in the record used  to create the stamp hash:

# PHIActivityGold

- [ ] Verification payload
    ```json
    valid: true / false,
    record: {
       ... // Unique payload identifying user
    }
    ```
- [ ] the attribute `valid` must always be false if the stamp verification fails
- [ ] record must contain the following attributes:
    - 1 or more attributes uniquely identifying the user:
        - an ETH address - it should always be lower case (not checksummed)
        - an email (in case of Google for example)
        - the users unique ID (like for Facebook, Twitter, Github)        
- [ ] never should the payload contain a field named `pii`
    - this field is reserved for internal use
- [ ] the provider name must be globally unique (and should not have been used). This is because the provider name will be included in the record used  to create the stamp hash:
