### ISSUE TITLE
Integrate Holonym Stamp to Gitcoin Passport

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1234]
### User Story:
As a user of Holonym (https://www.holonym.id/)
I want to verify my phon number or government id quickly using ZK proofs
So that I can prove I am a unique human and earn more stamps

### Acceptance Criteria
GIVEN I have have minted a Holo at app.holonym.id and 
GIVEN I have proved uniqueness at app.holonym.id/prove/uniqueness
WHEN I verify my holonym stamp
THEN I should earn the credential of Holonym (Gov't ID)

Verifications / credentials should include:
* Proven uniqueness using Holonym with government ID

This should be featured flagged OFF for Production (We'll want to wait until Alex can review and score before turning it on for users)

#### Product & Design Links:
<links>

#### Tech Details:
- Checking what identity record they use to (if so) asymmetrically hash a unique identifier associated with the Passport holder.
- Holonym team has created a PR - https://github.com/gitcoinco/passport/pull/794/files

#### Notes/Assumptions:
- This passes a risk assessment by Alex and we trust their ability to review KYC / Gov't ID
- This depends on #1124

**Comment by chibie** [comment]
Moved this to blocked because I am unable to receive the one-time code for phone number verification in the [Holonym app](https://app.holonym.id)

@nutrina passed the first mobile number verification but couldn't receive the one-time code during government ID verification.

We have created support tickets in the Holonym's Discord community

**Comment by chibie** [comment]
Update: I was able to verify my mobile number after removing it from the DND list of my network provider. I'm moving this back to in progress as I have also verified my government ID

**Comment by chibie** [comment]
# Checklist
## Provider: HolonymGovIdProvider

- [x] the provider name must be globally unique (and should not have been used). This is because the provider name will be included in the record used  to create the stamp hash:
- [x] Verification payload
    ```json
    valid: true / false,
    record: {
       ... // Unique payload identifying user
    }
    ```
- [x] the attribute `valid` must always be false if the stamp verification fails
- [x] record must contain the following attributes:
    - 1 or more attributes uniquely identifying the user:
        - an ETH address - it should always be lower case (not checksummed)
        - an email (in case of Google for example)
        - the users unique ID (like for Facebook, Twitter, Github)        
- [x] never should the payload contain a field named `pii`
    - this field is reserved for internal use
