### ISSUE TITLE
Integrate Civic Stamp to Gitcoin Passport

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1335]
### User Story:
As a user of Civic
I want to verify my information (captcha, KYC, or biometric data) quickly and easily
So that I can prove I am a unique human and earn more stamps

### Acceptance Criteria
GIVEN I have have minted a Civic pass
WHEN I verify my Civic stamp
THEN I should earn one of the Civic credentials

Verifications / credentials should include:
- CAPTCHA Pass - Holds a Civic CAPTCHA Pass
- Uniqueness Pass - Holds a Civic Uniqueness Pass
- Liveness Pass - Holds a Civic Liveness Pass
- ID document Verification (IDV) Pass - Holds a Civic ID document Verification (IDV)' ? Not sure this is live on EVMs yet.

#### Product & Design Links:
(see PR) 

#### Tech Details:
https://github.com/gitcoinco/passport/pull/1294

#### Open Questions:

- [x] This passes a risk assessment by Olsen and we trust their ability to provide a unique ID to prevent Sybil attacks
- [ ] Do we remove ID Verification since that is only available on the Sol chain?

**Comment by dankelleher** [comment]
A quick comment on the second open question - ID verification is coming to EVM chains very soon (this month)

**Comment by lucianHymer** [comment]
Hey @dankelleher! I left a [comment](https://github.com/gitcoinco/passport/pull/1294/files#r1240176110) on the PR, let me know if you'd like to discuss!

**Comment by lucianHymer** [comment]
Also, how exactly does civic on EVM work right now? Is there an end-user-facing way for me to create the pass NFT on Ethereum? Looks like the NFT contract is restricted to some gatekeeper addresses, but I can't really tell what's going on past that w.r.t. acquiring the NFTs myself with one of my ETH addresses.

**Comment by lucianHymer** [comment]
I've been following up with the Civic team in Telegram

**Comment by lucianHymer** [comment]
@erichfi and @Jeremy-Gitcoin, a few notes:

- When testing, to avoid needing to spend gas, go ahead and choose Goerli as the network in your wallet before trying to verify the stamp. The sidebar has a note that you should choose your intended network before trying to get the stamp.
- By default, it's going to help you claim your pass on Ethereum. Which is expensive for users
- Normally Civic writes to Polygon by default. But they've set up this UI for us so that it uses the user's current network instead
- The reason for all of this is that currently, if the user changes their chain in the oauth UI, it'll also change the chain in the passport app. Which causes the app to refresh. Which essentially breaks the oauth flow
- We should probably follow up on this by 1) preventing the UI from refreshing when the selected network changes and/or 2) preventing changes in the oauth window's network from affecting the main passport UI's network (we're doing something similar with the second-wallet flow, see app/signer/utils.ts and app/public/signer.html, see note on lines 94-963 of utils.ts, which potentially could throw off the oauth flow? not certain)
