### ISSUE TITLE
Increase Concurrency in Celery Workers

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1359]
### User Story:
As a backend developer,
I want to increase the concurrency in Celery workers,
So that the system can process tasks more quickly when queues are full.

### Acceptance Criteria
GIVEN the task queues are full,
WHEN the system starts more Celery workers,
THEN the CPU usage should increase and the system should process tasks more quickly.

#### Product & Design Links:
N/A

#### Tech Details:
This task involves adjusting the Celery worker settings to increase concurrency, possibly by reducing the allocated CPU and/or MEM and increasing the maximum number of workers.

Do a load test to understand the number of workers needed.

#### Open Questions:
1. How much should we increase the maximum number of workers?
2. What's the optimal allocation of CPU and/or MEM to achieve higher worker concurrency without overloading the system?

#### Notes/Assumptions:
Assumes that increasing worker concurrency will allow the system to process tasks more quickly when queues are full, thereby improving overall system performance.

**Comment by lucianHymer** [comment]
When first digging into this, it seemed like switching Celery over to use gevent threading would really help. The idea being that we don't need to be blocking (consuming workers) when waiting on the DB, and mostly our workers are just waiting on the DB. This would hopefully stop our current situation where we're not using our available CPU.

However, gevent isn't playing nice with the Django DB operations. I haven't been able to get it all working yet, but I'm seeing results similar to this. https://zapier.com/engineering/why-zapier-doesnt-use-gevent-yet/

I think I'm going to abandon going down this route. There doesn't seem to be a mature way to use django/celery/gevent together

**Comment by lucianHymer** [comment]
I will do some more testing after the production release this week

**Comment by lucianHymer** [comment]
I still need to run the 1000 user tests with k6, I've reached out to support to see if they can forgive the local tests run with --out=cloud

But here are my findings so far:
More CPUs is the biggest factor. A task with 16 vCPUs is way faster than 16 tasks each with 1 vCPU (even with --pool=solo, which is faster than normal but still much slower than fewer, larger tasks) or 8 tasks each with 2vCPU, etc. One reason is apparently that multiple workers (tasks) need to repeat messages a lot more, so it's best to use as few workers as possible, and just beef those workers up so they can each handle more processes.

The 16 vCPU server was showing almost 0 delay in the UI during 100 user load tests.

We cannot use --pool=gevent or eventlet because django isn't greenlet-safe. We would need to significantly refactor in a way that probably wouldn't even make sense.

The default, --pool=prefork, is supposed to run 1 process per CPU core. And this is supposed to generally be the most efficient configuration. However, I noticed significant gains in setting a concurrency to higher values. When the default concurrency was used, the queues were getting overwhelmed (load average greater than the # of processes). Double the number of vCPUs seems to work really well (i.e. for the 16 vCPU task, set the worker to a concurrency of 32). Setting it higher seems to be counter-productive, presumably because of additional messaging overhead. With a higher than CPUx2 concurrency, the memory usage scales linearly with the # of processes and the CPU utilization actually moderately declines.

So, I think we should do a 16 vCPU task with a concurrency of 32.

I'm still dialing in the auto-scale numbers, but the above configuration does do a good job of utilizing the CPU so I think we can set it to around 60. The larger load tests might also change this.

**Comment by lucianHymer** [comment]
With larger # of users (1000), the auto-scaling with larger CPUs was not working.

With a few large workers (16vCPU), tasks are processed quickly but they're mostly just waiting on the DB so the CPU usage is low so they do not auto-scale. With many small workers (0.25vCPU), the CPU usage actually is higher and auto-scaling works, but this is way less efficient (celery likes fewer top-level work and wastes time duplicating messages when there are more workers) and this method basically doesn't work (too slow to catch up to demand spikes).

Nick has a ticket around measuring queue size here (https://github.com/gitcoinco/passport/issues/1360) so maybe we can use that as a metric instead of CPU usage.

I am going to leave the current worker set up as-is, and we'll do the same as we've been doing and manually scale these up as necessary.
