### ISSUE TITLE
[Spike] Improve backend call efficiency

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#1371]
Can we be more efficient with any of our backend calls?

Outcome: Clear understanding of how, where, and why are backend calls are coming from and issues created to improve the efficiency of those calls.

#### Product & Design Links:
<links>

**Comment by lucianHymer** [comment]
Why do we do this resolveName and comparison, instead of just doing `const valid = await provider.lookupAddress(payload.address);` ? I can't think of any reason, and it's doubling our alchemy usage for this stamp. It bears investigation though, there's a bit of complexity to ENS records and we should check I'm not overlooking anything.


![Image](https://github.com/gitcoinco/passport/assets/19908762/93d86212-2703-4d4d-812b-1ae6ac050e2a)

**Comment by lucianHymer** [comment]
We can definitely cache token amounts for GTC (2 calls to 1 call) and ETH (3 calls to 1 call), which is huge

**Comment by lucianHymer** [comment]
NFT ops account for about half our IAM's usage, and that's about to be cut in half.

For the remaining changes, I think we're roughly reducing calls from 8 to 4 on average.

So this should halve our usage!
