### ISSUE TITLE
Auto-Update and Conditional Rescoring Feature for Gitcoin Passport Scorer's Instances

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1400]
### User Story:
As a Developer,
I want my scoring instances to automatically update with any changes made to the scoring model by Gitcoin, and only re-score already scored passports when the scoring endpoint is hit,
So that I can maintain accurate scoring without unnecessary system load and without manual intervention.

### Acceptance Criteria
GIVEN I have created a weighted scorer and that I have scored any number of passports with my scorer
WHEN the default weights are updated by Gitcoin
AND I score the same passports containing the same attestations again (by calling the `registry/submit-passport` api)
THEN I get back the new score based on the new updated weights

AND

GIVEN I have created a weighted scorer and that I have scored 10 passports with my scorer
WHEN the default weights are updated by Gitcoin
AND I read the score by accessing the `registry/score/<scorer_id>/<address>` api
THEN I get back the initial score based on the initial weights

#### Tech Details:
- The auto-update feature needs to be extended to conditionally trigger re-scoring based on whether the scoring or reading endpoint is hit.
- This conditional re-scoring mechanism needs to ensure that it does not cause unnecessary system load or disrupt the regular functionality of the scoring instance.

#### Open Questions:
How do we ensure the scoring endpoint only re-scores when necessary? What mechanism can be put in place to achieve this?

#### Notes/Assumptions:
This feature requires careful design and testing to ensure it functions correctly without causing disruptions or performance issues.

**Comment by Jeremy-Gitcoin** [comment]
Defaults will be hardcoded
No way in this version to have Erich, Alex or Jeremy update via the UI (requires Eng push)

**Comment by Jeremy-Gitcoin** [comment]
@erichfi Default = scoring weights, these will be hardcoded and pushed by developers vs. being flexible and able to be updated in the UI

**Comment by nutrina** [comment]
@erichfi @Jeremy-Gitcoin 
I would propose reformulating the acceptance criteria for clarity:

GIVEN I have created a weighted scorer and that I have scored any number of passports with my scorer
WHEN the default weights are updated by Gitcoin
AND I score the same passports containing the same attestations again (by calling the `registry/submit-passport` api)
THEN I get back the new score based on the new updated weights

AND

GIVEN I have created a weighted scorer and that I have scored 10 passports with my scorer
WHEN the default weights are updated by Gitcoin
AND I read the score by accessing the `registry/score/<scorer_id>/<address>` api
THEN I get back the initial score based on the initial weights

Does this sound correct?

**Comment by lucianHymer** [comment]
We actually want to do a bulk re-score when we update the weights. And if they query getScore during one of these bulk updates, the score should have a status of "BULK_RESCORE" or something like that.

**Comment by lucianHymer** [comment]
- [ ] Add BULK_PROCESSING score status
- [ ] Adjust existing status checks in passport and scorer
- [ ] Add mechanism to overwrite weights for existing scorers
- [ ] Add mechanism for re-scoring (with currently unused celery queue)
- [ ] Add django command for re-weighting and re-scoring

**Comment by lucianHymer** [comment]
For LIFO, rescoring should work fine b/c whoever has the Stamp for a particular <hash, provider> will be the only one who is ever able to have it. So we can rescore in any order.  We will have to make a small code tweak since we'll potentially have multiple scorings w/ the same hash occurring at basically the same time, which we wouldn't really have had before. Instead of deleting stamps at the beginning of scoring we should mark them as stale, then validate the current submission and mark those stamps as non-stale, then delete the still-stale stamps. Otherwise, we could mess up deduplication.

For FIFO, we should get the right results if we rescore in ascending order of last_score_updated. However, along the way, we will mess with the most recent deduplication. Perhaps we should mark them all as BULK_PROCESSING and keep it that way until every single FIFO score is rescored. I think this makes sense. There's probably a more efficient way to do it, but I'm not sure if we have sufficient data. We can also just exclude FIFO scorers from rescoring for the time being.

**Comment by lucianHymer** [comment]
Documented the steps here: https://www.notion.so/gitcoin/Passport-Scorer-Technical-Documentation-62bdf2ab993a48f7995734f8dd57964c?pvs=4#a4b4b95cc59c4579adddef5f35bdac60

**Comment by lucianHymer** [comment]
For testing on the review server, really we just want to make sure the scoring updates didn't break scoring or de-duping. So maybe try getting your score, then using another wallet with a duplicate and making sure it does not get counted, and then re-checking your original score.

As far as the re-scoring process goes, I have already run the rescoring process on the staging server data and it worked great.
