### ISSUE TITLE
Understanding Hash Generation for NFT-Based Stamps Deduplication

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1456]
**Objective:**
This SPIKE aims to investigate the method of hash generation for various NFT-based stamps (like ENS, NFT holder) used for the deduplication process. The purpose is to understand whether token/contract IDs are included in the hash generation for these stamps, and if not, evaluate the potential benefits and technical feasibility of incorporating token/contract ID hashing for the deduplication process.

**Method:**
1. Review the current hash generation process for each NFT-based stamp and identify the data used in generating these hashes.
2. If token/contract IDs are not currently included in hash generation, identify potential vulnerabilities or inefficiencies that may arise as a result.
3. Evaluate the potential benefits of incorporating token/contract ID into the hash generation for the deduplication process.

**Expected Outcomes:**
- [ ] A clear understanding of the current hash generation method for each NFT-based stamp and whether token IDs are included.
- [ ] A thorough evaluation of the potential benefits and drawbacks of incorporating token/contract ID into hash generation for each NFT-based stamp.
- [ ] Technical considerations for implementing token/contract ID into hash generation for each type of NFT-based stamp.

**Timeline:**
Spend one work day at most on this.

**Comment by hardiktheprogrammer** [comment]
@erichfi  I would like to work on this can you assign me this task

**Comment by nutrina** [comment]
The following platforms need to be checked:
- [ ] NFT
- [ ] ENS

**Comment by nutrina** [comment]
#### For NFT stamps

The current payload is:
```JS
{
    address: address,
    "NFT#numNFTsGte": "1",
}```

This means that a user could potentially move an NFT around across multiple wallets and then claim the stamp on all these wallets. Also it does not matter what NFT it is, we do not have a selected list of meaningful NFTs.

This could potentially be mitigated, if we would track individual NFTs (track the chain id, contract and id of the NFT).
This way we would be able to deduplicate this stamp, if the user moves it across wallets.

But unfortunately because of the big number of NFTs that are out there, and that a user may hold a big number of NFTs, it is not possible to track them all in a single attestation.

We could create a shortlist of NFT contracts and NFT collections and decide to track these.

Open points:
- how many NFTs musta user hold in order to qualify? If it is only 1, this is easy.
- but if we decide to require multiple NFTs, then we should think about changing the structure of the VC, to incorporate a list of hashes (instead of a single hash), in order to be able to track all the NFTs that we checked for that user.

**Comment by nutrina** [comment]
#### For ENS

The current payload is:
```js
{
        ens: reportedName,
}
```

This means we track domain name movements across accounts, hence we are able to deduplicate.
