### ISSUE TITLE
API Endpoint for Retrieving GTC Stakes on a Specified Ethereum Address

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1466]
### User Story:
As an admin of the Gitcoin Passport team,
I want to access an API endpoint that retrieves the total amount of GTC staked on a specified Ethereum address,
So that I can monitor and analyze the stake distribution and the influence of particular participants within the Gitcoin Passport community.

### Acceptance Criteria
GIVEN an admin of the Gitcoin Passport team has access to the API
WHEN the admin makes a GET request to the specific API endpoint (e.g., /addresses/{address}/gtc_stake)
THEN the API should return the total amount of GTC staked on the specified address by others, in a suitable data format (e.g., JSON).

#### Tech Details:
The API endpoint should be a GET request to a URL following this structure: /addresses/{address}/gtc_stake. The returned data should be formatted in JSON for ease of use and compatibility with various client-side applications. The access to this API endpoint should be restricted only to the admins of the Gitcoin Passport team, using suitable authorization and authentication mechanisms.

#### Open Questions:
- What will be the preferred method of admin authentication for accessing this API?
- How should we handle non-existent or invalid Ethereum addresses?
- Do we want to build a similar API endpoint to handle multiple addresses at once?
- Should the staking data also include historical data or just the current amount staked?

#### Notes/Assumptions:
We assume that every address to be queried will be a valid Ethereum address. The feature is expected to be used for understanding the stake distribution among Gitcoin Passport community participants by the admin team. Admin-level access restrictions need to be implemented to ensure proper rate limiting.

**Comment by lucianHymer** [comment]
Here's a script that will query the graph for a user's stake info, given a round ID and an address. The script has help text explaining the outputs--run `./stakes.sh -h`

The round name is included in the output, just as a sanity check since we don't usually refer to the rounds by their ID (the current round is ID 3).

We could also set this query up in postman, just using the same info as the cURL request at the bottom of this script. I'm happy to help with this.

The graph API key is in plaintext in this script. I've hosted it in a spot where only github people have access to it. It's fine to share, I can always revoke the key if needed. It's just used for this. Just try not to post the script anywhere public.

https://drive.google.com/file/d/1b15N6W_49Fri0qPEBfy0FmgC2KYyoU2d/view?usp=drive_link
