### ISSUE TITLE
Trusta Labs Stamp Integration

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1566]
### User Story:
As a Passport holder,
I want to verify my profile with the Trusta Labs stamp and have the results logged in a dedicated table,
So that I can showcase my unique humanity to the community and ensure transparency in the verification process.

### Acceptance Criteria
GIVEN I verify my Trusta Labs stamp on my Passport profile,
WHEN my Trusta Labs score is between -1 and 60,
THEN my profile should display a "No Sybil signs detected" verification stamp from Trusta Labs,
AND my unique humanity score should be increased by 1.54.

WHEN a Trusta Labs API call is made for verification,
THEN the result of the call, including timestamps, passport addresses, and Trusta Labs scores, should be logged in a dedicated table, separate from the credential issuance.

#### Product & Design Links:
![Trusta 1](https://github.com/gitcoinco/passport/assets/59769856/c95881ff-6b38-4422-98c2-a20f86d819e3)

#### Tech Details:
- API Endpoint: `https://www.trustalabs.ai/service/openapi/queryRiskSummaryScore`
- Test API Call:
```
curl -X "POST" "https://www.trustalabs.ai/service/openapi/queryRiskSummaryScore" \
     -H 'Authorization: Bearer [TOKEN]' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "address": "0xbe778865781aa618309a2c82dc5a8b563a024d62"
}'

```

_Note: Replace [TOKEN] with the actual token and the address with the desired Ethereum address._

Additional docs: https://trustscan.readme.io/reference/getting-started-with-your-api-1

#### Notes/Assumptions:

- The Trusta Labs score interpretation:
  - 80+: Indicates a Sybil account.
  - 20 or lower: Default score for a Non-Sybil account.
  - Further score range explanations will be provided by Trusta Labs for better clarity.
- The unique humanity scoring weight for the Trusta Labs stamp will be 1.54, migrated from the GitPoap stamp.
- This stamp should be part of the 1-click-web3 verification flow.

**Comment by trustamaster** [comment]
A more clear explanation of Trusta Labs Sybil score: The Trusta labs score has the value ranged from 0 to 100, where the higher the score, the more Sybil risk of the addresses. Besides, there are two negative integers -2 and -1 of the score to indicate two corner cases. More specifically,
1. -2 means "Out of scope for TrustScan's Sybil analysis due to insufficient on-chain activity". (With fewer than 3 transactions, TrustScan does not have enough behavioral data points to make a reliable risk assessment.). If an address has been scored by Trusta labs of -2, then the suggestion is "NOT Issuing Stamp" 
2. -1 means "High Value addresses，No apparent Sybil risk detected by TrustScan
(Some hub addresses and their connected addresses exhibit high volumes of activity and interactions, leading them to be accessed as high value accounts.)". If an address has been scored by Trusta labs of -1, then the suggestion is "Issuing Stamp".
3. score = [0,60], then it indicates that there is no signs of Sybil risks detected. In this case, the suggestion is "Issuing Stamp".
4. For score = [60,80], [80,90] and [90,100], the indications are LOW/MEDIUM/HIGH Sybil risk detected. In all these cases, the suggestion is "NOT Issuing Stamp" .

**Comment by digitalmnt** [comment]
@erichfi / @Jeremy-Gitcoin / @trustamaster  could you all provide us with the access token described here: https://trusta-labs.gitbook.io/trustalabs/trustscan#3.-sample-code
