### ISSUE TITLE
Hypercerts Stamp Verification Issue After Recent Minting

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1598]
**Overview**
A user encountered an inconsistency with the Hypercerts stamp verification process. Despite recently minting Hypercerts stamps, the user was able to successfully verify them, which contradicts the stipulated requirement that stamps should be held for more than 15 days prior to verification.

**Steps To Reproduce**

1. Go to the stamp verification page without any Hypercerts stamps in the wallet.
2. Attempt to verify Hypercerts stamps.
3. Observe the verification failure due to the absence of eligible Hypercerts stamps.
4. Navigate to the Hypercerts app.
5. Mint new Hypercerts stamps (user minted 3 stamps).
6. Return to the stamp verification page.
7. Attempt to verify the newly minted Hypercerts stamps.

**Observed  behavior**
The system successfully verified the Hypercerts stamps even though they were freshly minted and did not meet the "Held for more than 15 days" requirement.

**Expected behavior**
The system should have rejected the Hypercerts stamp verification since the stamps were not held for the required duration of more than 15 days.

**Screenshots**

**Additional context**
This issue was specifically observed with the Hypercerts stamp. It's crucial to determine if this behavior is unique to Hypercerts or if it's a broader system-wide issue. Further investigation is needed to ensure the "Held for more than 15 days" condition is being correctly enforced, especially for Hypercerts stamps.

**Comment by digitalmnt** [comment]
@erichfi it looks like we mis-understood the Hypercert schema when implementing this. The [creation](https://hypercerts.org/docs/developer/querying#output-3) date that we are using represents the creation date of the Hypercert as a whole, not the mint date of the user's portion of the hypercert. Imo this has a similar level of legitimacy but up to you on how to proceed! So the current logic is setup so that a user can go in and claim their portion of a hypercert and as long as that hypercert is greater than 15 days old passport will issue the VC
