### ISSUE TITLE
GTC Staking Credentials Dashboard in Redash

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1711]
### User Story:
As a Product Manager,
I want to have a dedicated dashboard in Redash for GTC staking credentials,
So that I can gain comprehensive insights into the distribution and engagement levels for each credential type.

### Acceptance Criteria
GIVEN that I have access to Redash,
WHEN I navigate to the dedicated GTC Staking Credentials dashboard,
THEN I should see a breakdown that shows the number of holders for each type of credential.

#### Product & Design Links:
<links>

#### Tech Details:

- Create a new dedicated dashboard in Redash.
- Utilize SQL queries to gather data from our backend database.
- Leverage Redash’s built-in visualization tools for optimal display.
- Ensure real-time or minimum interval updates (e.g., every 24 hours).

#### Open Questions:

- What other metrics could be beneficial to include in this dedicated dashboard?
- Are there any specific data filters (e.g., date range, credential type) that would be useful?

#### Notes/Assumptions:

- The creation of this dashboard assumes that the data for all GTC staking credentials is available in our database.
- Real-time updates are ideal but will depend on system capabilities.

**Comment by lucianHymer** [comment]
Here's the dashboard! https://redash.api.scorer.gitcoin.co/dashboard/gtc-staking-credentials

There is a table and chart for all credentials, and another table that shows the credentials created/updated in a date range. By default, this is the last 7 days.

Old credentials are overwritten, so if you look for example at the credentials created last year, it'll be a low number since most have been overwritten by new credentials this year. For most queries, you probably want to look at ranges ending today, e.g. the last 7 days, or one month ago to today, or the last 24 hours.

Let me know what you think!
