### ISSUE TITLE
OAuth Verification Issue for Multiple Web2 Stamps in Reverification Flow

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1866]
**Overview**
During the stamp reverification process within the Gitcoin Passport application, users with multiple Web2 OAuth stamps encounter an issue. The OAuth verification popup functions correctly for the first stamp but fails to trigger for any subsequent Web2 OAuth stamps.

**Steps To Reproduce**

1. Go to the Gitcoin Passport stamp reverification page.
2. Initiate the reverification process for multiple Web2 OAuth stamps.
3. Successfully complete the OAuth verification for the first stamp using the popup.
4. Attempt to verify a second Web2 OAuth stamp.

**Observed  behavior**
The OAuth verification popup that works for the first Web2 stamp does not trigger for the second or additional Web2 stamps. This prevents the completion of the reverification process for multiple Web2 stamps.

**Expected behavior**
The expected behavior is that for each Web2 OAuth stamp reverification, an OAuth verification popup should trigger, allowing the user to authenticate and verify each stamp individually.

**Screenshots**

**Additional context**

**Comment by aminah-io** [comment]
When you say the popup doesn't appear for subsequent, is the user also not able to re-verify their stamps? @erichfi

**Comment by aminah-io** [comment]
@erichfi it looks like this issue is caused by the browser blocking popups. Is this a bug report from support?

My recommendation is to have a tooltip or similar to let users know to allow popups from the Passport site, even if temporarily.

There is an issue with Github, however, it's the only one that doesn't continue along the flow to sign the message, so still looking into this one.
