### ISSUE TITLE
[CHORE] Pulumi settings for production

### ISSUE THREAD

**Issue by nutrina** [gitcoinco/passport#188]
Just dropping here some ideas that we should probably put in practice:
- `{ retainOnDelete: true }` for S3 bucket -> we want to protect this from accidental deletion: https://www.pulumi.com/docs/intro/concepts/resources/options/retainondelete/
- ensure that the certificateValidationDomain and the alb have the dependency to certificate set: `{ dependsOn: certificate }` set. As we have learned, pulumi does not track this dependency well.

**Comment by kammerdiener** [comment]
Finalizing a few of these and will be moving this to review.

**Comment by kammerdiener** [comment]
Updates are here: https://github.com/gitcoinco/passport/tree/production-settings

These are ready to be pushed in, but I have not changed these since this does include some changes to the Load Balancer. Tried to test on some other accounts, but want to be ready to revert staging if this breaks everything.

**Comment by leoneric** [comment]
@kammerdiener, the settings look good for testnet, but have not yet been ported to mainnet as far as @nutrina can tell. What's the status of this?

**Comment by kammerdiener** [comment]
We had some issues with Ceramic HealthChecks. Have the changes just need to test.

**Comment by kammerdiener** [comment]
Updates are made in production now: https://github.com/gitcoinco/passport/tree/production-settings
