### ISSUE TITLE
[BUG] Incorrect Calculation of Available Points in Idena Stamp Identity States

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1898]
**Overview**
The current implementation in the Idena stamp under Identity State inaccurately calculates the available points by summing up all the points of the credentials. This approach is misleading as the credentials under Identity State are mutually exclusive, meaning a user can only hold one state at a time.

**Steps To Reproduce**

1. Navigate to the Idena stamp section under Identity State.
2. Observe the total available points displayed.
3. Claim any one of the available credentials.
4. Note the change in the total available points.

**Observed  behavior**
The system incorrectly sums up the points of all credentials to display the total available points. This does not reflect the actual scenario where a user can only have one credential at a time.

**Expected behavior**
The expected behavior should be as follows:

- Before a user claims any credential, the system should display the points of the credential with the highest value as the total available points for that section.
- After a user has claimed a credential, the system should adjust the available points to reflect the highest point credential minus the points of the credential claimed by the user.

**Screenshots**

**Additional context**
This issue leads to a misunderstanding of the potential points a user can earn, as it falsely inflates the available points. Correcting this will provide a more accurate and transparent user experience. It's important to adjust this calculation to align with the mutual exclusivity of the credentials under the Identity State.

**Comment by lucianHymer** [comment]
Hmmmmm.

So technically, this also means that the score ring showing your score out of 100 is somewhat misleading, since you can't get 100 points.

I would rather we just make it so that these stamps aren't mutually exclusive. In other words. the "Human" stamp would imply the "Newbie" and "Verified" stamps. Then re-weight accordingly.

Same issue with the Cyberconnect stamp (premium should imply paid).


Otherwise, we have to encode some concept of mutual exclusivity in the stamp definitions. Which is a fairly difficult problem to solve in a non-clunky way.

Also, it seems to me (based on gut instinct and not any actual data science experience) like dealing with mutually exclusive stamps would make the scoring models considerably more difficult to generate. I think this probably limits us right now.


But also, maybe we do need to take the time to figure out mutual exclusivity in case there is actually a set of stamps down the road where mutual exclusivity is the only option?

What do you think?

**Comment by lucianHymer** [comment]
The work is wrapped up here, just need to review it!
