### ISSUE TITLE
Gitcoin Stamp Update for GG19

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1931]
We'll have two lists to import:
- matching eligible contributions
- squelch list, i.e., addresses that participated in the round but did not qualify for matching (incl. indicator why: deduplicatation or too low passport score)

**Comment by stefi-says** [comment]
hey. Here are the files to be included : 
[gg_19_inelegible_address.csv](https://github.com/gitcoinco/passport/files/13550655/gg_19_inelegible_address.csv)
[gg19_elegible_address_trx.csv](https://github.com/gitcoinco/passport/files/13550656/gg19_elegible_address_trx.csv)
 the one with _trx has the valid transactions ( filtered off the voters that are not eligible)

**Comment by digitalmnt** [comment]
Hey @stefi-says thanks for the documents! 

Would it be possible to get https://drive.google.com/file/d/11T21vWhRs83hCb1eLKzmS054WZYBpLUl/view?usp=drive_link in json format, assuming this spreadsheet contains all valid votes/contributions for a round? Wondering if we could also get them in the original format like what is found in https://indexer-production.fly.dev/data/10/rounds/0x7F9415761AfBd82E3Fe2FD9e878FA643184bC729/votes.json ? Asking since our existing scripts and DB are expecting them in that format. I would also be happy to assist making these changes? Just thinking that if you are already in the applying filtering it might be easy to out put the data in a different format.

**Comment by stefi-says** [comment]
Hey @digitalmnt , 
Yehap, this is all the valid transaction ( excluding the address with less than 20 passport score or sybil signal). I got the data from the Grants Stack DB , so it  came already in colunar format. I can change it to jsonl if necessary. I  would appreciate  some quick overview of if if you already have a function or a script to do so, as I have never done that, otherwise I can search and do it.

**Comment by digitalmnt** [comment]
Hi @stefi-says thanks so much that would be awesome! Here is a snippet on how to export  a pandas dataframe to jsonl. `df.to_json(orient='records', lines=True)`. Happy to make the changes as well! Just lmk where the script lives. Thank you!

**Comment by Bl9658ing** [comment]
Aww awesome

**Comment by stefi-says** [comment]
hey @digitalmnt , here are the files in json format as we talked:
- [all voter transactions](https://drive.google.com/file/d/1aPl-Qodh9jv0ltA1785ehnc5zmNKXzwf/view?usp=drive_link)
- [not eligible address](https://drive.google.com/file/d/1OsJjXp3uBU4jbHhlPsi_nn-B2ukZNSHv/view?usp=drive_link)
