### ISSUE TITLE
[BUG] NFT stamp issue

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#1979]
The following user is unable to claim the NFT stamp: 0xF4DCD710b890a478ea80249e62D0a69eE3D129b3

When I check their etherscan, I see that they have multiple NFTs, however on redash I see there are multiple wallets attached to the NFT in there.
![image](https://github.com/gitcoinco/passport/assets/88308638/5d706d1c-e0e3-4827-b5cc-8421cec81beb)

The issue is that, if a user has multiple NFTs, which one is being used for the NFT stamp, and in a case where one of their NFTs has been previously used in Passport, shouldn't passport check other NFTs?

**Link:** [Conversation with lucky013@dmail.ai](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/68601)

**Customer:** [lucky013@dmail.ai](https://app.intercom.com/a/apps/xaafeyri/users/657428983755c527b1b344a3/all-conversations)
**Customer ID:** 2e4ab541-1658-4956-bf37-a722922163b5
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xaafeyri/inbox/inbox/all/conversations/68601) when this issue is closed.

**Comment by jesuloluwao** [comment]
https://app.intercom.com/a/inbox/xaafeyri/inbox/admin/6462000/conversation/68537

**Comment by lucianHymer** [comment]
So it looks like for many of these users, the latest "NFT" is an ERC1155.

We're currently deduping NFTs on <contract address, token ID>, because for ERC721s that is guaranteed unique per NFT.

However, ERC1155 is a multi-token contract that can issue both fungible and non-fungible tokens. So you and I could both have a balance of tokens with contract address A and token ID 4.

We should probably just exclude these from the NFT stamp? From a brief look, I don't think you can really check whether or not a particular token ID is fungible in a standardized way.

If we use includeMetadata = true with our Alchemy call, it returns
```
{"contracts":[{"address":"0xffffffffb9059a7285849bafddf324e2c308c164","totalBalance":1,"numDistinctTokensOwned":1,
"isSpam":false,"tokenId":"0x04","name":"!fundrop Stickers","title":"Season 1 Participant",
"tokenType":"ERC1155","contractDeployer":"0x56d7303fb0d0781c2fbef962d7f9461bf416916f",
"deployedBlockNumber":17932947,"opensea":{"floorPrice":5.0E-4,"collectionName":"!fundrop Stickers",
"collectionSlug":"fundrop-stickers","safelistRequestStatus":"not_requested","lastIngestedAt":"2023-12-11T13:13:44.000Z"},
"media":[{"gateway":"https://nft-cdn.alchemy.com/eth-mainnet/8dc24b5956a40fcf3eb5f57e688f023c",
"thumbnail":"https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/8dc24b5956a40fcf3eb5f57e688f023c",
"raw":"https://media.contextcdn.com/fundrop/stickers/04.png","format":"png","bytes":263865}]}],"totalCount":2,
"pageKey":"c3038557-f627-47dd-a9e2-fe961936b364"}
```

So using the tokenType, we can filter for ERC721s. We'll want to increase our pageSize to fetch multiple tokens that we can search through.

However, I still don't know why the one user couldn't currently claim the stamp at all. Let me know when you have more info there.

**Comment by lucianHymer** [comment]
Per Jeremy: also update the text from "Currently, we only recognize NFTs..." to "Currently, we only recognize NFTs (ERC-721s)..."
