### ISSUE TITLE
Intuitive and Distinct Customization of Passport Dashboard and Scoring via Django Admin Panel

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#1990]
### User Story:
As a product manager/administrator of the Gitcoin Passport platform, I want to easily customize dashboard experiences, including setting up dashboard links, credential weights, and scoring algorithms, through a user-friendly Django admin panel interface. This customization will cater to a dynamic and personalized user experience, ensuring that the scoring system is both intuitive and accurately reflective of each passport holder's credentials.

### Acceptance Criteria
**Clear Credential Display:**
GIVEN the Django admin panel,
WHEN an admin configures the dashboard,
THEN they should be able to assign weights to each credential, ensuring that only credentials with a weight greater than 0 are visible to the user.

**Dynamic Scoring System:**
GIVEN the credential weighting system,
WHEN a passport holder's score is calculated,
THEN it must be the sum of the weights of the credentials they possess, with the scoring metrics on the front end using this recalculated score.

**Custom URL Paths:**
GIVEN a specific dashboard configuration,
WHEN an admin sets up or edits a dashboard,
THEN they can define a unique URL segment/path for direct access, separate from other dashboard configurations.

**Real-time Updates:**
GIVEN any changes in credential weights,
WHEN these changes are saved,
THEN the user interface should immediately reflect these changes in both credential visibility and scoring.

**Scoring Widget Customization:**
GIVEN the customization interface,
WHEN naming the scoring metrics and setting up URL paths,
THEN admins should be able to assign distinct names and URLs, which will be reflected in the scoring widgets and dashboard access.

#### Tech Details:

- Enhancements to Django models for clear and distinct credential weight assignments and unique URL paths.
- Creation of a straightforward scoring algorithm that aggregates weighted credentials.
- Front-end design modifications for immediate reflection of scoring and credential display changes.

#### Open Questions:

- What user interface elements can be introduced to make the customization process more intuitive for admins?
- Are there any specific user feedback mechanisms that should be included to verify the effectiveness of the customization?

#### Notes/Assumptions:

- The platform should maintain a balance between customization flexibility and user interface simplicity.
- The design should be future-proof, allowing for easy updates and modifications.

**Comment by nutrina** [comment]
Open question:

Clear Credential Display:
1. to hide credentials I would use a **hidden** list, instead of hiding stamps with weight 0. This is much easier to handle, it is more explicit.
2. the **custom** weights of the stamps would be handled in the scorer
  - **Attention**: whenever we update the weights we should not do that for the custom scorers.

Dynamic Scoring System:
1. not sure how to handle this, the default scorer is configured both in the UI and in the BE:
  - the score for the default scorer is calculated in the BE
  - shall we extend the BE implementation or shall we re-implement the call to calculate a score from the UI, depending on which dashboard a user is
  - also who is responsible to trigger the recalculation of the score? Gitcoin from the Passport App, the integrator via the API, or both? Right now it is the integrator via the API.
  
Custom URL Paths:

Real-time Updates:
- see section **Dynamic Scoring System**

Scoring Widget Customization:
- no questions

**Comment by nutrina** [comment]
Also, we should split this up:
1. First we need to have:
  - a custom dashboard only that is displayed on the custom path
2. (depends on 1)
  - implement the custom widget
3. (depends on 1)
  - implement the custom scoree:
    - custom weights - editable from the scorer in the django admin
    - update scripts to avoid changing weights for custom scorers
    - handling / triggering of score calculation / recalculation for custom scorers

**Comment by lebraat** [comment]
Answering some questions posed above:

Q - whenever we update the weights we should not do that for the custom scorers. The question is: shall we notify our integrators about our updates, maybe they will want to adjust ...? Or we don't need to communicate this at all?
another aspect: what happens when we add / remove stamps? This might required adjustments in the weights ...


A - We need to communicate these changes IMO. Even though they are choosing a different custom weight, it is still important for them to know what we know about the effectiveness of each Stamp, which is effectively communicated via our updates to weights. This also goes or the addition and subtraction of Stamps. 

I'm hoping to partner with PMM to put together a developer-specific newsletter that we can use to better communicate announcements like this to developers. We should also post about updates like this to our passport-dev-support Discord channel. 

---

Q - do we disable bringing stamps on-chain?

A - I'd suggest not. This is a revenue stream for us and we should protect that. If they really don't want us to have that enabled, we should offer a saas fee to them, which would help us recoup lost revenue. 

--- 

And some feedback. By further moving toward this use case, we should expect questions about creating a unique stamp set, and with it, a tough decision about whether we want others to be able to create Stamps that we don't support or want to be associated with our brand.

**Comment by Jeremy-Gitcoin** [comment]
@erichfi and @nutrina I agree we should probably split this up given the 3 suggested above:

(1) custom dashboard only
(2) Implementing the custom widget
(3) implementing the custom score (I think about this as a custom component on the widget e.g. some might want a custom score others not)

Where does the stamp hiding selection fit? Is that part of 1 or 2?

**Comment by Jeremy-Gitcoin** [comment]
When the user lands on the integrators website
GIVEN I am a user and I go to the integrators website
AND I have no previous passport
THEN the first step in the flow is the integrator will call our API and check for the score for their scorer ID.
(A) If the user has an existing Passport they will get the score for the integrator scoring ID 
(B) If the user does not have a Passport we will return
This should function exactly as it works for partners today. User lands on the site, does an action, they submit the passport and get a score, and then prompt the user to take action based on that score.

GIVEN I am a user and I go to the integrators website
AND I have have a passport scored with the default scorer only
THEN ... ? 
(same as the first scenario)

GIVEN I am a user and I go to the integrators website
AND I have have a passport scored with custom scorer owned by this integrator
THEN ... ?
(same as the first scenario)

When the user lands on the custom passport dashboard

GIVEN I am a user and I am redirected to the custom passport dashboard
AND I have no previous passport
THEN ... ?
(user will have a score of 0 for both the default humanity and the custom widget, the new user flow will function identical to the existing new user flow)

GIVEN I am a user and I am redirected to the custom passport dashboard
AND I have have a passport scored with the default scorer only
THEN ... ? // do we calculate the score for the custom scorer ?
(Yes, see first scenario above, we'd calculate the new scorer id score and display that in the custom widget next to the existing default unique humanity score)

GIVEN I am a user and I am redirected to the custom passport dashboard
AND I have have a passport scored with custom scorer owned by this integrator
AND I have claimed new stamps since my last visit to this dashboard
THEN ... ?
It would recalculate the new score and have that updated

GIVEN I am a user and I am redirected to the custom passport dashboard
AND I have have a passport scored with custom scorer owned by this integrator
AND I have deleted stamps since my last visit to this dashboard
THEN ... ?
Same as previous, we'd recalculate the new updated score based on the scoring ID 

Given the score update(s) if it's difficult we could have the user take an action like 'refresh custom score' but i'd prefer for that to be automatic, even if it's a spinner like we used to have on the site that recalculated that in real time and then updated to tell the user
