### ISSUE TITLE
[BUG] Coinbase Oauth failing

### ISSUE THREAD

**Issue by Jeremy-Gitcoin** [gitcoinco/passport#2008]
**Overview**
Details, details, details

**Steps To Reproduce**
1. Complete coinbase identity verification
2. Go to Coinbase stamp
3. Start the oauth process
4. Get a connection error (Brave) or white screen (metamask mobile)

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by digitalmnt** [comment]
This appears to be confined to chromium browsers on mobile(metamask browser). I was able to authenticate via brave/arc/chrome on mac desktop and safari/chrome on mobile iOS.

The error also seems to apply to all outh processes. I received the same blank screen using the metamask browser when authenticating with twitter. 

I wasn't able to find the root of the issue. I'm able to see mobile logs via safari mobile on my mobile device but unfortunately coinbase oauth is successful using safari. Putting this back into prio since I will be ooo next week. It seems to have a relatively low impact but would be good to get addressed

**Comment by lucianHymer** [comment]
It looks like [metamask mobile just doesn't support Oauth](https://github.com/MetaMask/metamask-mobile/issues/3515), they said to use walletconnect instead (which worked for me on iOS Chrome).

Still looking into Brave mobile

**Comment by lucianHymer** [comment]
Alright so on iOS with both Firefox and Brave, I needed to go to `Settings > Block Popups` and disable this. Then, I was able to use oauth correctly.

@jesuloluwao FYI
