### ISSUE TITLE
[BUG] User's with lens profiles from a different contract are unable to claim the stamp

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#2014]
**Overview**
We are getting quite a number of users reaching out regarding the inability to claim Lens stamp. On a [previous issue](https://github.com/gitcoinco/passport/issues/1949), I was able to understand that we're using this [smart contract](https://polygonscan.com/address/0xe7E7EaD361f3AaCD73A61A9bD6C10cA17F38E945#readProxyContract) to verify the lens ownernship. But in the case of many of these users, when I checked this contract, the profile belonged to another wallet.

Looking deeper into the case, it seems the user purchased the lens profiles on places like https://element.market/ethereum and opensea. Checking in these places I could confirm the ownership of the lens profiles to be the user.

I would understand why these users aren't getting the stamp so that I can give them an update.

**Observed  behavior**
An example user that reached out:
- Wallet address: 0x3Dc1e70ece943a4191ab1b12CeFdE00964a660C0
- Purchased on element: https://element.market/assets/polygon/0xdb46d1dc155634fbc732f92e853b10b288ad5a1d/130373.
In this lens profile, I see the contract is different from the one we might be using https://polygonscan.com/address/0xdb46d1dc155634fbc732f92e853b10b288ad5a1d

Another user bought theirs on opensea: https://opensea.io/assets/matic/0xdb46d1dc155634fbc732f92e853b10b288ad5a1d/130197 with the same contract as above

**Expected behavior**
I would expect that they get the stamp after owning the profiles. But if there's something off about how the stamps were gotten, then I'd like to know in order to provide an update to the users

**Comment by lucianHymer** [comment]
Hey @jesuloluwao! So these users own the Lens Profile NFT, but they have not linked a Lens Handle to the profile.

A handle is required for this stamp.

Thanks!

**Comment by lucianHymer** [comment]
@jesuloluwao I just double checked the second NFT you'd linked. Was this user also having issues? Or was that just another example of a profile using the same contract?

**Comment by jesuloluwao** [comment]
@lucianHymer they were having the issue

**Comment by jesuloluwao** [comment]
@lucianHymer so there's some confusion then on how to get these handles. Do you have some infomration on how to get the handles so I can share with the users (it's also a bit confusing to me)

**Comment by lucianHymer** [comment]
> @lucianHymer they were having the issue

Ah okay, so the NFT was sold earlier today. It looks like the previous owner, who probably reported the issue, does not own any handles.

I don't have experience claiming a handle, but it looks like it corresponds to ownership of one of these NFTs https://opensea.io/collection/lens-handles

**Comment by jesuloluwao** [comment]
Another example https://polygonscan.com/nft/0xdb46d1dc155634fbc732f92e853b10b288ad5a1d/104927

It looks like we're only considering this contract as a valid handle https://polygonscan.com/token/0xe7e7ead361f3aacd73a61a9bd6c10ca17f38e945#readProxyContract

But could it be that this contract also give handles?
How can we distinguis between this for users so that we're clear on when they should receive the stamp and when they shouldn't https://polygonscan.com/address/0xdb46d1dc155634fbc732f92e853b10b288ad5a1d#readProxyContract

**Comment by lucianHymer** [comment]
Ultimately, it's because the Lens API is telling us that those addresses don't own any handles. You can see in this example that under "properties", the previous owner is listed as the "owner". And when I query the Lens API, it tells me that the old address still owns this handle.

I can see that the profile NFT here: https://polygonscan.com/nft/0xdb46d1dc155634fbc732f92e853b10b288ad5a1d/104927
is linked to the handle NFT here: https://polygonscan.com/nft/0xe7e7ead361f3aacd73a61a9bd6c10ca17f38e945/45273094926012707486278957229983137256002788874739797588044935120395578018527 <- This is the NFT for the handle @gurmeetkaur.lens

The handle is what we care about for the stamp. I think the user just needs to own the handle NFT.

@erichfi Do we have a good way to get in touch with Lens so we can ask them how to best communicate these concepts to the user, and to confirm that our method of checking for a user's `ownedHandles` is the correct way to do things?
