### ISSUE TITLE
[BUG] Gitcoin Grants Stamps disappeared when I tried to update the stamps

### ISSUE THREAD

**Issue by jesuloluwao** [gitcoinco/passport#2025]
**Overview**
While attempting to update my GG stamps, I initially saw a message that said my stamps have been successfully removed (even though I didn't remove).

Now when I try to add them back, I am unable to even though I have donated to over 60 projects and >$100 value. You can find my donation history here https://explorer.gitcoin.co/#/contributors/0x69f9e121702461eA52F627A6147ea3c6dc2DEF31. My wallet address is 0x69f9e121702461eA52F627A6147ea3c6dc2DEF31. Attached is the JSON response from when the stamp failed.

[passport (9).json](https://github.com/gitcoinco/passport/files/13871342/passport.9.json)

Meg also reported the same issue.

**Comment by digitalmnt** [comment]
@erichfi here is updated documentation on the import process based on changes made for this ticket https://www.notion.so/gitcoin/cGrants-Data-Grants-Data-onchain-82e0bbff530241778119d546b65bc072. Hoping the next import will run a bit smoother

**Comment by jesuloluwao** [comment]
@digitalmnt does your fix also solve the issue of me loosing my stamps for previous rounds even though I was only flagged as sybil (allegedly :)) in GG19? If for some reason, I donate with more than 1 wallet in GG19, it shouldn't invalidate my previous donations in previous rounds where I wasn't Sybil

**Comment by digitalmnt** [comment]
No it doesn't, that was why I assigned it to Stefi since I'm not 100% sure what went into determining the squelch list. My changes make it so that if you donated on both GG18 and 19 and are marked as sybil for GG18 but you are not marked as sybil on GG19 you contributions to GG19 will still be counted toward your stamp. I did this due to the discussion here ⁠[Users unable to claim GG18 stamp](https://discord.com/channels/562828676480237578/1171076545494929469/1194245258465267794)⁠ where if your score is not sufficient for one round but is sufficient for another you can still claim a stamp for the round you qualify for
