### ISSUE TITLE
[BUG] New Lens Handles are not getting Passport stamp

### ISSUE THREAD

**Issue by YukiPL** [gitcoinco/passport#2224]
**Overview**
The new 8 Matic Lens Handles are not getting verified by passport.

**Steps To Reproduce**
1. Go to Lens and purchese the new 8 Matic Handles
2. Go to Passport and verify the Lens stamp
3. See Error

**Observed  behavior**
The new handle is not getting verified.

**Expected behavior**
The Handles should be good to verify the Lens stamp.

**Some affected addresses**
0x318f3b76582f63BE848f3Db0FAF2143Bb2AE4C60

0x2C1e085E946Fa5dE10d129B45f47Ab5D68BEacd2

0x5a2F65af8e53E0828c8250525eB9a70d657A6Bd5

0xE7C2E550D9e46047A0Df81cCF42Ca8F0bccc08c5

0x8575db8C72eE6fAe0650D9DD71b25E6efa5d57fB

**Additional context**
From Gerald: 
All of the above should work.
I have checked here https://api-v2.lens.dev/ , they all qualify.
I ran this query (just replace the value in the for field):
 query OwnedHandles {
        ownedHandles(request: {
          for: "0x8575db8C72eE6fAe0650D9DD71b25E6efa5d57fB"
        }) {
          items {
            id
            ownedBy
            fullHandle
          }
        }
      }

**Comment by nutrina** [comment]
Will be closing this without merging in the alternative implementation to check for the handle.
We agreed that we should stick to the Lens API instead of finding a workaround for the API issues.
This is a problem that Lens should address on their API end (problem = indexing delay, we only get the handles of a user after hours of being created).
