### ISSUE TITLE
Initiate and Manage 1-Click Verification Post-Onboarding

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2436]
### User Story:
As a user who has just completed the onboarding flow,
I want to automatically start the 1-Click Verification process,
So that I can ensure my stamps are verified while still being able to use other functionalities of the dashboard.

### Acceptance Criteria
GIVEN I have completed the onboarding flow and am redirected to the dashboard,
WHEN the 1-Click Verification process begins,
THEN the score display should enter a "loading" state and the verify button for stamps should be disabled, while other dashboard functionalities remain operational.

GIVEN I already have a stamp that we find,
WHEN the flow completes
THEN we should reissue this stamp even though I already possess it.

#### Product & Design Links:
Figma Link: https://www.figma.com/file/FOOlLEFaBt87atw6CPkA5P/Passport-App?type=design&node-id=8886%3A2839&mode=design&t=A95YBtu2alZO5RG0-1

#### Tech Details:

- Implement the dashboard so that during the 1-Click Verification process, the score widget shows a "loading" state and the verify button in the stamp sidebar is disabled.
- Ensure all other dashboard functionalities, not related to stamp verification or score calculations, are accessible and operational.

#### Open Questions:
- [ ] What is the right copy for the loading Scorer widget?

#### Notes/Assumptions:
- Assumes that the system has the necessary back-end support to manage the state of various UI components based on the verification status.

**Comment by digitalmnt** [comment]
Do we have text for the tooltip?

![Image](https://github.com/gitcoinco/passport/assets/6887938/dfdd66b2-d9ac-4bcb-8806-f2c595c95527)

**Comment by digitalmnt** [comment]
@erichfi heres a video showing whats going on behind the scenes. https://drive.google.com/file/d/1hL6NS2mKMmU3kFPTlLKmIZRuEwMHb1Nb/view?usp=sharing Happy to pair on it tomorrow as well.

1. This is strange I'm able to claim stamps that are not found in the one click verification process while testing on review.
2. In the video you can see that Verifying is shown within the button. Unfortunately its only shown for a brief moment.  This is because the `/check` request is necessary to determine which stamps we should disable. I tried to demonstrate this in the video. Unfortunately the check request accounts for the majority of the time spent processing  
3. This is due to us having scaled down resources for the staging/review envs causing the iam requests to take longer. Unfortunately the `/check` request does take longer than other requests because it is doing a lot more than any other endpoint. As part of the load testing ticket I suggested implementing this endpoint as a lambda which should increase performance. It was also the first endpoint to start having problems once load increases regardless of resources.

**Comment by digitalmnt** [comment]
Just waiting on review
