### ISSUE TITLE
Investigate and Fix IAM Bottleneck

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2515]
### User Story:
As a Passport user,
I want to complete the 1-click verification flow without timeouts
So that I can verify my identity quickly and efficiently.

### Acceptance Criteria
GIVEN the current implementation of the IAM system
WHEN a user initiates the 1-click verification flow
THEN the process completes without timeouts

GIVEN potential external API delays/rate limiting
WHEN the IAM bottleneck is identified
THEN appropriate fixes are implemented to prevent timeouts

#### Tech Details:

- Investigate current IAM bottlenecks, focusing on external API rate limits and delays
- Implement fixes based on investigation findings, potentially involving:
  - Optimizing API calls to avoid rate limits
  - Introducing retries or fallback mechanisms
  - Enhancing IAM system’s internal handling to be more resilient to delays

#### Open Questions:

- [ ] Which external APIs are causing the rate limits?
- [ ] What specific improvements can be made to the IAM system to handle external delays better?

#### Notes/Assumptions:
- Initial investigation points to external API rate limiting as the primary cause of bottlenecks
- Fixes may involve both code and infrastructure changes

**Comment by digitalmnt** [comment]
@nutrina I ran the load tests again, this time against these changes https://github.com/gitcoinco/passport/compare/load-testing-with-timeout. Here all `/check` requests should throw a 408 if the service is functioning correctly. 

Here are the results

![Image](https://github.com/gitcoinco/passport/assets/6887938/1e297a49-74de-4188-88ba-82eca2b824b9)

As you can see the service initially begins throwing 408s, gets overwhelmed, then begins throwing 504s. This is consistent with the load tests I previously ran and what I my suggestions from the previous set of load testing. 

Wanted to note this here because it differs from the suggestions in this ticket around tracking third party APIs. 

In my opinion we should attempt to optimize the `/check` endpoint if possible, and if not move it to a lambda function to see how it handles the load there. Lmk if you see something I am missing!

**Comment by digitalmnt** [comment]
Updates

1. Begin scaling iam service at 25% of cpu utilization instead of 50
2. Execute checkTypes in a fully async way. Instead of synchronously within a platform. Performed better when load testing
3. Removed static endpoint. Performed poorly when load testing and afaik it is unnecessary

**Comment by digitalmnt** [comment]
I bumped up the default task count to 2 for our prod env as part of this change. Here are the results I had while loading testing with 1000 users. We will be find most of the time with 1 task but 2 will make it much more performant. 

![Image](https://github.com/gitcoinco/passport/assets/6887938/b55c51b8-d39a-45c7-bcf5-78430cdcd471)
![Image](https://github.com/gitcoinco/passport/assets/6887938/ce2e3d3a-272f-4a11-896e-ec1e6243bffa)
