### ISSUE TITLE
Losing stamp from my passport

### ISSUE THREAD

**Issue by phsiao** [gitcoinco/passport#254]
I had two stamps and were both anchored.  I tried to add a third on 6/18 and been watching it to see if it gets anchored, but today I found that the stamp is lost.  My passport streamid is `k2t6wyfsu4pfz5mylgt9d20zu0ns70b1k4nawokhidibmss6z2hmzd1igytsji`.

The CommitID for the third stamp is `k6zn3rc3iwgu9up8aay0r12zmzbwtyv38650bik6kzre2yp4msbojjzcg6seef7rzjuta51gg93l6iuhzn6fyi82xjf2l7fg5bcy5yhzxkv1909yi7m08xa` and the CID is `bagcqcerahrvdgzpb4ugsduayer66goa2ib7tlyqhwrurpu76sbsepdd3d4xa`.  It was in my stream but it is no longer there.

[cerscan](https://cerscan.com/mainnet/stream/k2t6wyfsu4pfz5mylgt9d20zu0ns70b1k4nawokhidibmss6z2hmzd1igytsji) captured the snapshot from when the third stamp is still there, and that is how I recovered my third CommitID.

The actual stamp is still there, its streamid is `kjzl6cwe1jw14a7h1tlb0zjwqvi0j2ltst9852gau3b20o9yiagkvtystuvnepf` and it is anchored.

**Comment by phsiao** [comment]
The commit is still visible in Ceramic's community gateway: `curl --location --request GET 'https://gateway.ceramic.network/api/v0/streams/k2t6wyfsu4pfz5mylgt9d20zu0ns70b1k4nawokhidibmss6z2hmzd1igytsji'`.  But it is not in Passport's gateway: `curl --location --request GET 'https://ceramic.passport-iam.gitcoin.co/api/v0/streams/k2t6wyfsu4pfz5mylgt9d20zu0ns70b1k4nawokhidibmss6z2hmzd1igytsji'`.

**Comment by stbrody** [comment]
@phsiao, when I look at those two links - the stream on the public gateway or on gitcoin's node - I see the same state for both.  Please note that gitcoin was hitting a bug in Ceramic when they launched that caused data loss.  That bug has since been fixed and gitcon upgraded to the patched version on the afternoon of Monday June 20th.  It's likely that the issues you were seeing were a result of that bug
