### ISSUE TITLE
Customizable Onchain Sidebar for Custom Dashboards

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2591]
### User Story:
As a custom dashboard user (e.g., Linea/Verax),
I want to hide certain chains from the onchain sidebar,
So that I can focus on the specific chain(s) relevant to my needs.

### Acceptance Criteria
GIVEN a user on a custom dashboard accesses the onchain sidebar,
WHEN the sidebar opens,
THEN it should only show the chains set by the team in Django admin.

GIVEN an admin accesses the Django admin panel,
WHEN they navigate to the custom dashboard configuration,
THEN they should see an option to select which chains are visible in the onchain sidebar.

GIVEN an admin selects or deselects chains in the Django admin panel,
WHEN they save the changes,
THEN the selected configuration should be stored in the database and reflected in the custom dashboard sidebar for the user.

#### Tech Details:
- Backend:
  - Update Django admin to allow customization options for the onchain sidebar.
  - Implement a form or checkbox interface for selecting/deselecting chains.
  - Ensure the selections are stored in the database.
- Frontend:
  - Modify the sidebar component to dynamically display only the selected chains based on the user’s configuration.
  - Ensure the sidebar updates in real-time or upon next load to reflect admin changes.
- Database:
  - Store the user's sidebar configuration efficiently.
  - Ensure quick retrieval and update of configuration data.

#### Notes/Assumptions:

- Assume that users will typically only need one chain displayed, but flexibility should be allowed for multiple chains if required.
- The customization feature should be intuitive and easily accessible within the dashboard settings.
- This customization should not affect other users’ dashboard settings.
- Let's also adjust the Linea hardcoded custom dashboard as part of this: https://github.com/gitcoinco/passport/issues/2588

**Comment by nutrina** [comment]
Topic 1:
The Verax dashboard is currently hardcoded.
We'll need to make the list of supported chains for onchain passport configurable and add the list of the supported chains to it's config.

Topic 2:
We'll also need to add selecting the list of chains for a dashboard in the admin.
This can be a simple comma separated list of chain-ids. The help text of the field should list all supported chains, so that the editor does not have to look them up externally.

Topic 3:
Implement the customisation in the app.
