### ISSUE TITLE
Bug: Passport requests to login via metamask signature on every visit/reload of the app

### ISSUE THREAD

**Issue by sirpy** [gitcoinco/passport#272]
In clay.self.id once you login with metamask it remembers your identity on subsequent refreshes/reloads.
on passport it will ask you to sign the login to ceramic on every reload.

**Comment by shavinac** [comment]
Hi, the discrepancy is because `clay.self.id` website is using the 3ID Connect system to authorize Ceramic DIDs, while Gitcoin Passport is using a new feature of Ceramic called `CACAO` for authorization.

This new feature requires users to sign in with Ethereum to authorize a CACAO session, and the current version of Ceramic used does not yet support persisting session keys, so users will need to re-sign for each session. However the Ceramic team is working on session persistence as an upcoming feature.

Gitcoin Passport has been working closely with the Ceramic team to use this new CACAO feature. Please reach out in the Ceramic discord if you have further questions about CACAO.

**Comment by shavinac** [comment]
Closing now that later versions of Ceramic can support DID sessions (https://developers.ceramic.network/reference/accounts/did-session/), and there is a new issue (https://github.com/gitcoinco/passport/issues/304) to add this feature to Passport app.
