### ISSUE TITLE
White Screen and Glitchy Scroll Rendering Issues on Mobile Safari

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#2732]
**Overview**
When using Mobile Safari, users sometimes encounter a white screen when scrolling. There are also issues with glitchy and rerendering problems, overlay issues, and occasional scroll repainting. Additionally, the scrolling sometimes starts from the top again, despite not navigating back to the top.

**Steps To Reproduce**

1. Open Mobile Safari.
2. Navigate to the Passport application (provide URL or specific page).
3. Begin scrolling down the page.
4. Observe the errors described below.

**Observed  behavior**

- White screen appears intermittently while scrolling.
- Glitchy and unstable rendering, with content flickering.
- Overlay elements (such as modals or dropdowns) not displaying correctly.
- Scroll repainting issues, leading to visual artifacts.
- Scrolling unexpectedly resets to the top of the page without user intervention.

**Expected behavior**

- Smooth and stable scrolling without white screen interruptions.
- Proper rendering of all elements, with no flickering or glitches.
- Overlay elements display correctly and consistently.
- Continuous scrolling without unexpected resets to the top of the page.

**Screenshots**
N/A

**Additional context**

- OS: iOS
- Browser: Mobile Safari

**Comment by tim-schultz** [comment]
Safari on mobile iPhone 11 is working well for me. I'm on 4g LTE so wondering if the issue was network speed when this issue was occurring. 

I looked into how we can optimize our current fe. Since we are using next but not using the next router we are not taking advantage of next's built in code splitting by route/page https://nextjs.org/learn/dashboard-app/navigating-between-pages#automatic-code-splitting-and-prefetching.

The linked PR moves the page components to the components dir so they are not statically built. It then uses next's dynamic imports to dynamically import the components when needed. 

It does decrease the initial load size which seems like it could help, but unsure the full implications in terms of speed

Before:
<img width="532" alt="Screenshot 2024-08-28 at 5 06 16 PM" src="https://github.com/user-attachments/assets/7c79d175-2538-414f-87d1-777d4bbb9de8">

After: 
<img width="520" alt="Screenshot 2024-08-28 at 5 07 04 PM" src="https://github.com/user-attachments/assets/70548f0a-da31-474f-84e2-6bb051b814d7">
