### ISSUE TITLE
API v2 Documentation Update

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#3075]
### Objective:
Conduct a focused technical review of the API v2 documentation to ensure accuracy and completeness before finalizing.

Draft updates here: 
https://github.com/passportxyz/passport-docs/pull/47/files

### Scope of Work

1. Technical Accuracy Review:
  - Verify the technical details of each API endpoint, including methods, parameters, and responses.
  - Check consistency with the implemented API functionality.
2. Data Dictionary Evaluation:
  - Ensure that all data fields are accurately described and reflect current API behavior.
  - Identify any discrepancies between the documentation and the API's actual functionality.
3. Highlight Key Areas:
  - Note sections that require deeper technical validation.
  - Summarize findings and suggest specific focus points for further review if needed.

### Deliverable:
A technical feedback document highlighting discrepancies, errors, or areas needing further clarification.

### Timebox:
Complete the review and provide feedback within 1 day.

**Comment by tim-schultz** [comment]
@lebraat this looks great! I think the only part I found confusing was the threshold references. Mainly because we always return a threshold and passing_score value that references that threshold. This could also just be me :)

- For the below screenshot it could be useful to link to the [Verifiable Credential spec](https://www.w3.org/TR/vc-data-model-2.0/) 

![Image](https://github.com/user-attachments/assets/2b8b9496-ff4e-432b-b767-9b200bee0e0a)

**Comment by Jkd-eth** [comment]
@lebraat Let me know if you're good and we'll close this issue since it's not one we'll 'deploy'
