### ISSUE TITLE
[API] Add raw score and threshhold to payload of Binary Community Scorer

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#806]
Output
- Score = raw score
- Threshold = threshold
- Approved = boolean

Also make sure the threshold is right

**Comment by lucianHymer** [comment]
Okay I had an idea.

Ultimately, we're trying to communicate a score (binary or otherwise) and also allow users to see the details of why they did not pass the community's requirements if their scoring doesn't meet criteria (threshold). We want to  leave room for other types of scoring, perhaps with much more complex requirements.

So I say we return something like
```
{
  type: 'binary',
  score: '0',
  explanation: 'User had a raw weighted score of 23.24 which does not meet the threshold of 30'
}
```
or
```
{
  type: 'weighted',
  score: '23.24',
  explanation: 'User had a weighted score of 23.24'
}
```
or
```
{
  type: 'binary',
  score: '1',
  explanation: 'User had a raw weighted score of 23.24 which exceeds the threshold of 20'
}
```
etc..

**Comment by lucianHymer** [comment]
Note that this can't really be tested in the UI b/c we can't create Communities with binary scoring from the UI yet. I hacked together the right environment to test it in my workspace though.
