### ISSUE TITLE
[PASSPORT] Remove expired stamps from Passport

### ISSUE THREAD

**Issue by erichfi** [gitcoinco/passport#810]
As a Passport holder, I want to be able to remove expired stamps from my Passport so that I can keep it up-to-date. This includes being notified of the expired stamps and being able to initiate the removal process from the notification, as well as receiving confirmation that the stamps have been removed.

**Acceptance Criteria:**
GIVEN a Passport holder has at least one expired stamp in their passport
WHEN the Passport holder accesses their dashboard page
THEN a notification is displayed to the Passport holder with a button or link to start the removal process

GIVEN the Passport holder has initiated the removal process for their expired stamps
WHEN the removal process is completed
THEN a confirmation message is displayed to the Passport holder

Design files: https://www.figma.com/file/RIsPkjpIaeEc73SjLiHK2G/Passport?node-id=8679%3A68427&t=jmAUbpykOpICi4Lg-1

**Comment by schultztimothy** [comment]
Here is a WIP branch that began this implementation https://github.com/gitcoinco/passport/pull/new/810-remove-expired-stamps

**Comment by schultztimothy** [comment]
![Image](https://user-images.githubusercontent.com/6887938/214453438-5ae76d92-da3e-4f4d-a084-39a8d9febd6b.png)

Would it be acceptable to just display the platform name instead of the record value? Asking because what if more than one stamp is expired? 

Also should `Remove` delete all stamps within a platform? Or just expired ones?

**Comment by schultztimothy** [comment]
This should be ready for review on https://calm-term-4626.on.fleek.co/#/dashboard
