### ISSUE TITLE
[Bug] Prompt for signature without user action on passport.gitcoin.co

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#834]
**Current behavior**
When loading the passport.gitcoin.co page, the user is prompted to sign a message without any user action. This creates a poor user experience and security and erodes trust in the login experience.

**Expected behavior**
The prompt for a signature should only occur when the user clicks on the "Connect Wallet" button on the main homepage. The user should not be prompted to sign a message without explicitly requesting it.

**Comment by lucianHymer** [comment]
How do we want to handle this? Essentially there's two steps: connecting a wallet and signing the SIWE message.

When a user comes to the home page, we connect their wallet after they choose Connect. Then, we're loading the dashboard page and immediately prompting the user to sign a message. It is a bit jarring, especially for something security-centric like a signature.

I'm thinking we'll need to draw something up in Figma. Do we add a second step on the home page? Or add an overlay when the dashboard page is loading? Etc.

**Comment by Kweiss** [comment]
If the session is no longer alive, let's start from scratch... ie, if the session is dead, then let's assume someone needs to click "connect" before we try to load anything.

This has a few benefits: 1 - if a user has multiple wallets, they can select which one to actually connect (we wont assume their last session is where they want to be)
2- this does not cause the need for a different "sign" button or intertial

**Comment by nutrina** [comment]
@lucianHymer @chibie  do you mind linking a PR here?

**Comment by nutrina** [comment]
This is still in progress, tests are failing.

**Comment by nutrina** [comment]
@chibie @lucianHymer I don't think this works as expected, hence I am reopening this ....

**Comment by nutrina** [comment]
I have listed below what I understand that the expected behaviour is.
Please keep in mind, that connecting to passport is a 2-step process as (and not 1-step as in most dApps).

The user is required to:
1. connect his wallet
2. sign a message


GIVEN I am user navigating to https://passport.gicoin.co
AND My wallet (Metamask) is not connected to the https://passport.gicoin.co website
THEN I expect to see the landing page and remain there
AND I have to click the "Connect Wallet" button to connect my wallet and navigate to the Dashboard


GIVEN I am user who has just connected his Wallet (Metamask) to the  Passport page (https://passport.gicoin.co)
WHEN I am redirected to the passport Dashboard
THEN I am automatically required to sign a message for the self.ID session that authenticates me in Ceramic & Passport Scorer


GIVEN I am user with a valid self.ID session
WHEN I go to the https://passport.gicoin.co website website
THEN I am automatically redirected to the passport Dashboard


GIVEN I am user with an invalid self.ID session (can be expired)
WHEN I go to the https://passport.gicoin.co website website
THEN I expect to see the landing page and remain there
AND I have to click the "Connect Wallet" button to connect my wallet and navigate to the Dashboard


Maybe to make it very clear and explicit to the user we could use something like a flow wkzzard to guide the user through these steps:

![Image](https://user-images.githubusercontent.com/8137830/217529403-ac983d92-bc0a-4d3f-9e0f-2462cd8fefaa.png)
