### ISSUE TITLE
Ensure requester belongs to community when fetching scores

### ISSUE THREAD

**Issue by lucianHymer** [gitcoinco/passport#968]
The /score/ endpoints take a community_id parameter

We don't currently check to make sure it matches the API key's community.

We should check this, and perhaps add alternative endpoints which don't take a community_id but instead just assume the community from the API key.

**Comment by wslyvh** [comment]
Is this something that will likely happen or just posted as an idea? 

Maybe it should be configurable to allow communities to be open/public or private.
I can imagine having standard (e.g. Gitcoin Grant' scores) or 'community curated' mechanisms to be useful to the larger ecosystem. In other words, for simple use-cases I think just using someone else's scoring mechanism is often sufficient and I don't want to setup and require users to submit their passports to my specific community project.

**Comment by nutrina** [comment]
@wslyvh This is an interesting idea. I can definitely see the benefit of having "public" communities. But this is a different feature by itself, because I think that public communities / scorers should also have a public submission page for passports to be scored (which we currently don't have).
@erichfi @Kweiss  adding you here for context, we might want to track this feature request.

But for know we'll implement the original request in this ticket.
