### ISSUE TITLE
Redesigned home page for scorer.gitcoin.co

### ISSUE THREAD

**Issue by Kweiss** [gitcoinco/passport#971]
### User Story:
As a developer looking to integrate with Gitcoin Passport
I want to land on a branded site that reflects the rest of Gitcoin's branding
So that I can trust the resources and have a consistent experience

### Acceptance Criteria
GIVEN someone navigates to scorer.gitcoin.co
WHEN the page loads
THEN the new designs, layout and copy text should be present

#### Product & Design Links:
[Landing page designs](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=677%3A29273&t=SnTALj6Kc4pCCoAf-1)

#### Notes/Assumptions:
- [x] Brand colors and theme
- [x] Sign in with Ethereum button (and block native?)
- [x] copy text is updated
- [x] New logo in header is added
- [x] Footer changes are applied

**Comment by Etovardesign** [comment]
Hey @lucianHymer, I'm adding mobile views to all the pages.

[Landing Page Mobile Figma Designs](https://www.figma.com/file/ShlrWEZ3SVjYi31q0ehDva/Passport-S17?node-id=924%3A23919&t=XkWpOtO3L31z8wGG-1)

Also, regarding the logo comment, I converted it to a shape so we don't have to worry about finding the right font. Also, a note that on Mobile views, the tool wordmark (i.e. "Scorer", "Passport", etc.) is hidden. This is due to the reduced real-estate.

**Comment by lucianHymer** [comment]
Ready for review at https://main.d26qkvvv9tu48j.amplifyapp.com/

**Comment by Etovardesign** [comment]
@lucianHymer following up on spacing:

**Desktop**
- The spacing between the body copy and the "Sign-in with Ethereum" should be 40p.
- The footer elements should be fixed w/ a bottom margin of 48p (globally).

**Mobile**
- Spacing between the header and "Gitcoin" wordmark should be 24p.
- Footer should have a 48p top & bottom margin.

**Comment by lucianHymer** [comment]
@Etovardesign Thanks so much for the feedback! These updates are done and available for you to review at https://main.d26qkvvv9tu48j.amplifyapp.com/
